### ISSUE TITLE
Rename List to ListMD or something else

### ISSUE THREAD

**Issue by fakenickels** [InsidersByte/bs-material-ui#40]
Here https://github.com/InsidersByte/bs-material-ui/blob/master/src/MaterialUI.re#L1258

Because it overrides the real `List` module from OCaml once opened.
If you guys agree I can send a PR for this

**Comment by InsidersByte** [comment]
Hi @grsabreu!

It's generally not advisable to `open` the `MaterialUI` module locally, this is because it will clash with other modules.

If you do want to `open` it and use the standard library `List` module you can assign it to a variable at some point prior to opening `MaterialUI` (probably at the top of the file).

I realise that the README actually says to `open` the module, so I will update it to reflect the above :sweat_smile:
